/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentoriaRouteImport } from './routes/mentoria'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as EbookRouteImport } from './routes/ebook'
import { Route as CursoRouteImport } from './routes/curso'
import { Route as IndexRouteImport } from './routes/index'

const MentoriaRoute = MentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookRoute = EbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoRoute = CursoRouteImport.update({
  id: '/curso',
  path: '/curso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curso': typeof CursoRoute
  '/ebook': typeof EbookRoute
  '/guia': typeof GuiaRoute
  '/mentoria': typeof MentoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curso': typeof CursoRoute
  '/ebook': typeof EbookRoute
  '/guia': typeof GuiaRoute
  '/mentoria': typeof MentoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curso': typeof CursoRoute
  '/ebook': typeof EbookRoute
  '/guia': typeof GuiaRoute
  '/mentoria': typeof MentoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/curso' | '/ebook' | '/guia' | '/mentoria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/curso' | '/ebook' | '/guia' | '/mentoria'
  id: '__root__' | '/' | '/curso' | '/ebook' | '/guia' | '/mentoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursoRoute: typeof CursoRoute
  EbookRoute: typeof EbookRoute
  GuiaRoute: typeof GuiaRoute
  MentoriaRoute: typeof MentoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentoria': {
      id: '/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof MentoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook': {
      id: '/ebook'
      path: '/ebook'
      fullPath: '/ebook'
      preLoaderRoute: typeof EbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso': {
      id: '/curso'
      path: '/curso'
      fullPath: '/curso'
      preLoaderRoute: typeof CursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursoRoute: CursoRoute,
  EbookRoute: EbookRoute,
  GuiaRoute: GuiaRoute,
  MentoriaRoute: MentoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
